"""auth_user_secrets

Revision ID: 4891fb30795d
Revises: 9414d4f645c1
Create Date: 2026-01-30 10:23:14.832856

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4891fb30795d'
down_revision = '9414d4f645c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersecret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersecret_created_at'), 'usersecret', ['created_at'], unique=False)
    op.create_index(op.f('ix_usersecret_email'), 'usersecret', ['email'], unique=False)
    op.create_index(op.f('ix_usersecret_updated_at'), 'usersecret', ['updated_at'], unique=False)
    op.add_column('searchrun', sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.create_index(op.f('ix_searchrun_owner_email'), 'searchrun', ['owner_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_searchrun_owner_email'), table_name='searchrun')
    op.drop_column('searchrun', 'owner_email')
    op.drop_index(op.f('ix_usersecret_updated_at'), table_name='usersecret')
    op.drop_index(op.f('ix_usersecret_email'), table_name='usersecret')
    op.drop_index(op.f('ix_usersecret_created_at'), table_name='usersecret')
    op.drop_table('usersecret')
    # ### end Alembic commands ###
