"""init

Revision ID: 57b9136665f0
Revises: 
Create Date: 2026-01-28 09:25:48.686287

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '57b9136665f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Bootstrap core tables for a fresh sqlite install.

    Early versions of Sourceress created tables outside Alembic. In a fresh DB
    we need to create them here so later migrations work.

    We use SQLite's `IF NOT EXISTS` to avoid breaking existing installs.
    """

    from alembic import context

    if context.get_context().dialect.name != 'sqlite':
        # For non-sqlite, we assume a managed DB and migrations were created in order.
        # (Can be extended later.)
        op.add_column('candidate', sa.Column('email', sa.String(), nullable=False, server_default=''))
        op.add_column('candidate', sa.Column('email_source', sa.String(), nullable=False, server_default='none'))
        return

    # Candidate table
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS candidate (
          login TEXT NOT NULL PRIMARY KEY,
          html_url TEXT NOT NULL DEFAULT '',
          avatar_url TEXT NOT NULL DEFAULT '',
          name TEXT NOT NULL DEFAULT '',
          company TEXT NOT NULL DEFAULT '',
          location TEXT NOT NULL DEFAULT '',
          bio TEXT NOT NULL DEFAULT '',
          followers INTEGER NOT NULL DEFAULT 0,
          email TEXT NOT NULL DEFAULT '',
          email_source TEXT NOT NULL DEFAULT 'none',
          profile_json JSON NOT NULL DEFAULT '{}'
        );
        """
    )

    # SearchRun table
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS searchrun (
          id INTEGER NOT NULL PRIMARY KEY,
          created_at DATETIME NOT NULL,
          raw_query TEXT NOT NULL,
          location TEXT NOT NULL DEFAULT '',
          min_followers INTEGER NOT NULL DEFAULT 0,
          active_days INTEGER NOT NULL DEFAULT 180,
          status TEXT NOT NULL DEFAULT 'queued',
          processed INTEGER NOT NULL DEFAULT 0,
          total INTEGER NOT NULL DEFAULT 0,
          error TEXT NOT NULL DEFAULT ''
        );
        """
    )

    # CandidateScore table
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS candidatescore (
          id INTEGER NOT NULL PRIMARY KEY,
          run_id INTEGER NOT NULL,
          login TEXT NOT NULL,
          score REAL NOT NULL DEFAULT 0.0,
          reasons JSON NOT NULL DEFAULT '[]',
          FOREIGN KEY(run_id) REFERENCES searchrun(id),
          FOREIGN KEY(login) REFERENCES candidate(login)
        );
        """
    )

    # Useful indexes (IF NOT EXISTS supported on SQLite 3.8.0+)
    op.execute("CREATE INDEX IF NOT EXISTS ix_searchrun_created_at ON searchrun(created_at);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_searchrun_status ON searchrun(status);")

    op.execute("CREATE INDEX IF NOT EXISTS ix_candidatescore_run_id ON candidatescore(run_id);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_candidatescore_login ON candidatescore(login);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'email_source')
    op.drop_column('candidate', 'email')
    # ### end Alembic commands ###
