"""init

Revision ID: 57b9136665f0
Revises: 
Create Date: 2026-01-28 09:25:48.686287

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '57b9136665f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('email', sa.String(), nullable=False, server_default=''))
    op.add_column('candidate', sa.Column('email_source', sa.String(), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'email_source')
    op.drop_column('candidate', 'email')
    # ### end Alembic commands ###
