"""stack_runs

Revision ID: 9414d4f645c1
Revises: e6680fe06a5c
Create Date: 2026-01-28 13:48:31.576942

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9414d4f645c1'
down_revision = 'e6680fe06a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite needs defaults for NOT NULL columns.
    op.add_column('searchrun', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='github'))
    op.add_column('searchrun', sa.Column('stack_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('searchrun', sa.Column('stack_match', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='any'))
    op.add_column('searchrun', sa.Column('min_rep', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('searchrun', sa.Column('min_answers', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_searchrun_source'), 'searchrun', ['source'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_searchrun_source'), table_name='searchrun')
    op.drop_column('searchrun', 'min_answers')
    op.drop_column('searchrun', 'min_rep')
    op.drop_column('searchrun', 'stack_match')
    op.drop_column('searchrun', 'stack_tags')
    op.drop_column('searchrun', 'source')
    # ### end Alembic commands ###
