"""add_repo_seeds

Revision ID: 97754c6a030f
Revises: b2df34dcacf9
Create Date: 2026-01-28 09:36:31.557639

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97754c6a030f'
down_revision = 'b2df34dcacf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchrun', sa.Column('repo_seeds', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchrun', 'repo_seeds')
    # ### end Alembic commands ###
