"""contrib_filters

Revision ID: ad20f71d9a94
Revises: 2c5edf7d4fc2
Create Date: 2026-01-28 12:44:42.814821

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ad20f71d9a94'
down_revision = '2c5edf7d4fc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite needs defaults for NOT NULL columns.
    op.add_column('savedsearch', sa.Column('min_contribs', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('savedsearch', sa.Column('max_contribs', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('searchrun', sa.Column('min_contribs', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('searchrun', sa.Column('max_contribs', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchrun', 'max_contribs')
    op.drop_column('searchrun', 'min_contribs')
    op.drop_column('savedsearch', 'max_contribs')
    op.drop_column('savedsearch', 'min_contribs')
    # ### end Alembic commands ###
