"""your_message

Revision ID: b2df34dcacf9
Revises: fca3722dc563
Create Date: 2026-01-28 09:30:54.963181

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b2df34dcacf9'
down_revision = 'fca3722dc563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
