"""loc_company_filters

Revision ID: e6680fe06a5c
Revises: ad20f71d9a94
Create Date: 2026-01-28 13:09:23.823993

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e6680fe06a5c'
down_revision = 'ad20f71d9a94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite needs defaults for NOT NULL columns.
    op.add_column('savedsearch', sa.Column('location_include', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('savedsearch', sa.Column('location_exclude', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('savedsearch', sa.Column('company_include', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('savedsearch', sa.Column('company_exclude', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('searchrun', sa.Column('location_include', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('searchrun', sa.Column('location_exclude', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('searchrun', sa.Column('company_include', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('searchrun', sa.Column('company_exclude', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchrun', 'company_exclude')
    op.drop_column('searchrun', 'company_include')
    op.drop_column('searchrun', 'location_exclude')
    op.drop_column('searchrun', 'location_include')
    op.drop_column('savedsearch', 'company_exclude')
    op.drop_column('savedsearch', 'company_include')
    op.drop_column('savedsearch', 'location_exclude')
    op.drop_column('savedsearch', 'location_include')
    # ### end Alembic commands ###
