"""saved_searches

Revision ID: ecee30c37afd
Revises: 121a5f73bae6
Create Date: 2026-01-28 11:18:36.997911

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ecee30c37afd'
down_revision = '121a5f73bae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedsearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_seeds', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_followers', sa.Integer(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savedsearch_created_at'), 'savedsearch', ['created_at'], unique=False)
    op.create_index(op.f('ix_savedsearch_name'), 'savedsearch', ['name'], unique=False)
    op.create_index(op.f('ix_savedsearch_updated_at'), 'savedsearch', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savedsearch_updated_at'), table_name='savedsearch')
    op.drop_index(op.f('ix_savedsearch_name'), table_name='savedsearch')
    op.drop_index(op.f('ix_savedsearch_created_at'), table_name='savedsearch')
    op.drop_table('savedsearch')
    # ### end Alembic commands ###
