"""add_whatever

Revision ID: fca3722dc563
Revises: 57b9136665f0
Create Date: 2026-01-28 09:30:19.430245

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fca3722dc563'
down_revision = '57b9136665f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
